# Use containers
sudo: required

language: node_js
  
node_js:
  - "v6.9.0"
  
services:
  - docker

before_script:
  - ./setupAll.sh

# Build steps
script:
  - ./test.sh travis-compose.yml

after_failure:
  - docker-compose --file travis-compose.yml logs
