version: "2"

services:
  db:
    environment:
      DB_USER: "coliselia"
      DB_PASS: "siggame"
      DB_NAME: "coliselia"
      DB_PORT: "5432"
    build: db/
    ports:
    - "5432:5432"

  dbapi:
    environment:
      DB_USER: "coliselia"
      DB_PASS: "siggame"
      DB_NAME: "coliselia"
      DB_PORT: "5432"
      DBAPI_PORT: "3000"
    build: dbapi/
    ports:
    - "3000:3000"


